### ISSUE TITLE
Fakeroot-tcp

### ISSUE THREAD

**Issue by Lunchb0ne** [yuk7/ArchWSL2#11]
Do we still need fakeroot-tcp, we can just replace it with normal tcp in WSL2

**Comment by yuk7** [comment]
Yes,WSL2 don't need fakeroot-tcp.
We can use original fakeroot (icp).

**Comment by Lunchb0ne** [comment]
Yeah, so can we remove it and replace it with normal tcp in the image too?

**Comment by yuk7** [comment]
Ok.
I plan to replace fakeroot-tcp with fakeroot(icp) in the next release.

**Comment by yuk7** [comment]
I replaced fakeroot-tcp with original fakeroot(icp) in latest release.
https://github.com/yuk7/ArchWSL2/releases/latest
