### ISSUE TITLE
Docker WSL2 integration: /mnt/wsl size is zero

### ISSUE THREAD

**Issue by 0xBADDCAFE** [yuk7/ArchWSL2#13]
`/mnt/wsl` directory that mounted for Docker Desktop WSL Integration only have directory structure and does not have content. Some other distro (I have checked Ubuntu and Alpine) have contents for Docker Desktop WSL Integration.

`du -sh /mnt/wsl` and `ls -lR /mnt/wsl` output of ArchWSL2 and Ubuntu: 
https://gist.github.com/0xBADDCAFE/b0568f2ffd97a8b3d6c9b9dd7019737e

**Comment by yuk7** [comment]
I have question.
1. What is build number of Windows?
2. What is ArchWSL2 version?
3. Are other mount points working? (e.g. /mnt/c)

**Comment by 0xBADDCAFE** [comment]
Sorry for lack of information.

> What is build number of Windows?

2004 Build 19041.330

> What is ArchWSL2 version?

20062900

> Are other mount points working? (e.g. /mnt/c)

Yes.

**Comment by 0xBADDCAFE** [comment]
I tried about this issue now and fix it currently.

https://github.com/microsoft/WSL/issues/4377

```
wsl.exe --shutdown
```

I already tried this command when open this issue, but it didn't fix this then. I got it seems WSL2's problem, so can close this issue.

**Comment by yuk7** [comment]
Ok.
