### ISSUE TITLE
Why is this needed?

### ISSUE THREAD

**Issue by lackovic** [yuk7/ArchWSL2#14]
I am using [ArchWSL](https://github.com/yuk7/ArchWSL) on WSL2 as development platform, running [Docker](https://docs.docker.com/docker-for-windows/wsl/) and even [Linux GUI applications](https://github.com/lackovic/notes/tree/master/Windows/Windows%20Subsystem%20for%20Linux#run-a-linux-gui-application-in-wsl-2), with excellent performance and no issue whatsoever.

Could you spend a few words on why is this needed and what benefits it brings compared to ArchWSL?

**Comment by Lunchb0ne** [comment]
It uses less amount of custom hacks and keeps it closer to vanilla Arch.

You can also directly get the arch image via the website and import it into WSL if you want.

**Comment by yuk7** [comment]
ArchWSL2 has added a hack to run the systemd daemon by default, so that it can behave more like pure Arch Linux.

**Comment by lackovic** [comment]
@Lunchb0ne, @yuk7 thanks! Perhaps this is a useful information that would be well suited for the README.

Any ETA on when it could become stable?

**Comment by yuk7** [comment]
@lackovic 
There are still some outstanding bugs, so it will take some time for them to be resolved.

**Comment by lackovic** [comment]
> There are still some outstanding bugs, so it will take some time for them to be resolved.

In the README I only see this one:

_- Execute .exe on Linux directory (e.g. /etc /root /home)_

Are there others? If you make a comprehensive list with the details maybe me and somebody else can help fixing them.

**Comment by yuk7** [comment]
There used to be a bug in binfmt. (fixed #16)
I think there are potential bugs as issues are reported regularly.

It has not been reproduced in my environment, but a bug has been reported that the drive does not mount. #15
