### ISSUE TITLE
df report error after update to [ALPHA] 20062900

### ISSUE THREAD

**Issue by Sherlock-Holo** [yuk7/ArchWSL2#16]
I update the Arch2.exe to [ALPHA] 20062900 and restart Arch2 throuth `wsl --shutdown` and re-open the windows terminal

when I run `df -h` it reports 

> df: /proc/sys/fs/binfmt_misc: Too many levels of symbolic links

**Comment by yuk7** [comment]
I reproduced this issue.
Thank you for your reporting.

**Comment by yuk7** [comment]
temporary fix
execute this in shell:
```
mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc 
```

**Comment by Sherlock-Holo** [comment]
it fixed the problem.
look forward to the next release to fix it.

**Comment by yuk7** [comment]
I fixed this issue and added systemd-binfmt support in latest release .
https://github.com/yuk7/ArchWSL2/releases/latest
