### ISSUE TITLE
Realtime Clock Error

### ISSUE THREAD

**Issue by Yukigamine** [yuk7/ArchWSL2#18]
I'm getting an error after installing and trying to launch ArchWSL2. I have done both a normal install using Arch2.exe as well as side loading into the appx version. I get the same error on both.

I'm on a fresh windows install and the original ArchWSL runs just fine.

```
Arch2.exe
sleep: cannot read realtime clock: Invalid argument
sleep: cannot read realtime clock: Invalid argument
nsenter: cannot open /proc/16/ns/cgroup: No such file or directory
```

**Comment by yuk7** [comment]
You must use WSL2.
```
wsl.exe --set-version Arch2 2
```
