### ISSUE TITLE
Is it suitable for daily development

### ISSUE THREAD

**Issue by lijingrs** [yuk7/ArchWSL2#22]
I've enjoyed using WSL for a while.I really want to know if this can be used as a daily development system, because I am more concerned about stability,Looking forward to your reply.

**Comment by yuk7** [comment]
This distribution is still in alpha.
Updates can also damage your instance's system.

**Comment by lijingrs** [comment]
> This distribution is still in alpha.
> Updates can also damage your instance's system.



As I've used today, manually unmounting a disk can cause a system unrecoverable exception.If not, I don't think it's any different from a pure system.Anyway, I like it very much.Good luck!
