### ISSUE TITLE
"Press any key to continue" should be "Press enter to continue"

### ISSUE THREAD

**Issue by 0cyn** [yuk7/ArchWSL2#24]
I apologize for how stupidly small this is, and I'd PR it if the source containing that were here.

**Comment by yuk7** [comment]
Source is here: https://github.com/yuk7/ArchWSL2/blob/master/src/script.sh#L18

If you don't bother,please create PR.

**Comment by 0cyn** [comment]
Yikes, not sure how i missed that, thanks :)

**Comment by 0cyn** [comment]
No longer able to replicate the issue, although I did find that it needs to be ran in bash via `bash -c "read -t 5 -n 1 -s -r -p 'Press any key to continue...'$'\n'" `. It seems that Arch2.exe already spawns bash specifically, so I'm not sure what was going on earlier...
