### ISSUE TITLE
Process exited with code 9

### ISSUE THREAD

**Issue by Jacky2** [yuk7/ArchWSL2#3]
Why can't I open Archwsl2 after installing libffi,  System failure caused by libffi software

`pacman -S libffi`

[ Process exited with code 9 ]

**Comment by yuk7** [comment]
I think this issue is fixed in latest version
requires clean install.

https://github.com/yuk7/ArchWSL2/releases/latest

**Comment by yuk7** [comment]
Could you use latest version and clean install it?
https://github.com/yuk7/ArchWSL2/releases/latest

and Please run full system update...
```
pacman -Syu
```

**Comment by Jacky2** [comment]
Yes, I also found that updating the system could solve the problem. Thank you.

`pacman -Syu`
