### ISSUE TITLE
future of ArchWSL2

### ISSUE THREAD

**Issue by MorphBonehunter** [yuk7/ArchWSL2#30]
Hi @yuk7,
today i realize that you rename the repo from Arch Linux centric to systemd centric.
What does that mean for ArchWSL2? Did you end supporting/creating versions for WSL2?

**Comment by yuk7** [comment]
The current version of ArchWSL2 release is still in this repository.
Just as I separated the launcher project from ArchWSL, I plan to make this project more versatile in the future.

The current version of this has serious design bugs found, so I'll decide how to release it as soon as I can fix it.

**Comment by MorphBonehunter** [comment]
Ok, thanks for the info!

**Comment by MorphBonehunter** [comment]
just for cross reference if someone stumble about this issue...
ArchWSL2 has been discontinued: https://github.com/yuk7/ArchWSL/issues/164#issuecomment-732810336
