### ISSUE TITLE
Supplementary groups don't get added when starting a new session

### ISSUE THREAD

**Issue by zizzencs** [yuk7/ArchWSL2#4]
Steps to reproduce:

- WIN: install this on Windows 10 2004 on WSL2
- WIN: start a session
- LIN: set up sudoers to allow all for %wheel without a password
- LIN: set up a new user (zmezei)
- LIN: add the user to some supplementary groups (wheel and tfenv)
- LIN: logout
- WIN: change the default startup user to the new user, result:

```
PS C:\Arch> .\Arch.exe get --default-uid
1000
```

- WIN start a new session
- LIN: experience some strange behavior:

```
[zmezei@jane ~]$ id
uid=1000(zmezei) gid=1000(zmezei) groups=1000(zmezei)
[zmezei@jane ~]$ id zmezei
uid=1000(zmezei) gid=1000(zmezei) groups=1000(zmezei),998(wheel),1001(tfenv)
[zmezei@jane ~]$ ls -l /var/lib/tfenv/versions -d
drwxrwxr-x 3 root tfenv 4096 Jun  7 21:49 /var/lib/tfenv/versions
[zmezei@jane ~]$ touch /var/lib/tfenv/versions/testfile
touch: cannot touch '/var/lib/tfenv/versions/testfile': Permission denied
```

- LIN: "login" as the user:

```
[zmezei@jane ~]$ sudo su -l zmezei
[zmezei@jane ~]$ id
uid=1000(zmezei) gid=1000(zmezei) groups=1000(zmezei),998(wheel),1001(tfenv)
[zmezei@jane ~]$ id zmezei
uid=1000(zmezei) gid=1000(zmezei) groups=1000(zmezei),998(wheel),1001(tfenv)
[zmezei@jane ~]$ touch /var/lib/tfenv/versions/testfile
[zmezei@jane ~]$
```

I guess this is caused by the method you use nsenter here:
https://github.com/yuk7/ArchWSL2/blob/master/src/isocon_sh.sh#L17

According to nsenter's man page:

```
       --preserve-credentials
              Don't modify UID and GID when enter user namespace. The default is to drops supplementary groups and sets GID and UID to 0.
```

So it drops supplementary groups by default, and I guess it happens here as well.

**Comment by yuk7** [comment]
Thank you for reporting. 
It is a feature I haven't implemented yet.

That script runs as root. 
So we need to revert the running user in some way.

**Comment by yuk7** [comment]
Fixed that script and published new build!
Thank you!
