### ISSUE TITLE
error when login with normal account

### ISSUE THREAD

**Issue by TrT-TOT** [yuk7/ArchWSL2#5]
In the latest version 20060800, when setting default-uid to 1000 or set default-user to normal account, can't login system.

**Comment by yuk7** [comment]
I'm very sorry.
I reproduced this bug.
I made a mistake in setting the permissions.

**Comment by yuk7** [comment]
Could you execute this for fix permission?:
`Arch2.exe config --default-uid 0`
```
chmod 4755 /boot/init_wsl2/init_systemd
```

I re-uploaded zip. Thanks!🙇

**Comment by TrT-TOT** [comment]
By the way, Vmmem has a high cpu consumption even when no user processes are loaded. Is it due to WSL2 or Arch?

**Comment by yuk7** [comment]
It's a problem with both WSL2 and ArchWSL2.
WSL2 is a VM and therefore consumes a lot of computer resources.
And ArchWSL2 starts multiple daemons to run systemd.

You can stop the instance with this command:
```
wslconfig /t Arch2
```

**Comment by TrT-TOT** [comment]
Ok, thank you! The cost for using systemd is too high ^_^

**Comment by TrT-TOT** [comment]
Since I'm new to wsl, I wonder whether configuration in wsl will conflict with that in windows. For example, If I ask cpu to work in powersave mode in WSL, while set this as highperformance in windows, what would happen :yum:

**Comment by yuk7** [comment]
If you do that in WSL, it only applies in WSL.

The number of processors and memory limits used for WSL 2 can configuration with the `.wslconf` file.
If you are interested please see here:
https://docs.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by raphael-costa** [comment]
> Ok, thank you! The cost for using systemd is too high ^_^

Maybe a new issue would be a better place but this is indeed something to consider, perhaps it is simply not worth it.

**Comment by TrT-TOT** [comment]
> > Ok, thank you! The cost for using systemd is too high ^_^
> 
> Maybe a new issue would be a better place but this is indeed something to consider, perhaps it is simply not worth it.

In terms of my experience, [genie](https://aur.archlinux.org/packages/genie-systemd) is a good solution

**Comment by yuk7** [comment]
I fixed abnormal CPU usage and this issue.
I'm sorry for late fix.
