### ISSUE TITLE
There's a /usr/.bin folder created

### ISSUE THREAD

**Issue by rdbisme** [yuk7/ArchWSL2#6]
Is this normal? I would expect to find stuff inside `/usr/bin`. 

Moreover this creates problems with `cmake` and `CMAKE_ROOT`, since `/usr/.bin` is in the `PATH` before `/usr/bin` and `cmake` results moved in another directory.

**Comment by yuk7** [comment]
This is a bug.
Thank you for reporting.

**Comment by yuk7** [comment]
Fixed. I'm sorry for the late fix
