### ISSUE TITLE
Abnormal CPU usage?

### ISSUE THREAD

**Issue by cheng6563** [yuk7/ArchWSL2#7]
I no running other process, but vmmem cpu usage 30%.
Is this caused by systemd?

![TIM截图20200611110143](https://user-images.githubusercontent.com/15995816/84340413-3d1d4900-abd3-11ea-8bf6-f55be4c02e03.png)
![TIM截图20200611110219](https://user-images.githubusercontent.com/15995816/84340419-40b0d000-abd3-11ea-9e34-172601b6b837.png)

**Comment by walkthetalk** [comment]
same problem, ubuntu is ok, maybe it's related with systemd?

**Comment by chetgurevitch** [comment]
It's syncbin.sh

**Comment by yuk7** [comment]
Fixed. I'm sorry for later.
https://github.com/yuk7/ArchWSL2/releases/latest
