### ISSUE TITLE
uninstall 

### ISSUE THREAD

**Issue by ruizlenato** [yuk7/ArchWSL2#8]
How to uninstall with all files?

**Comment by yuk7** [comment]
`Arch2.exe clean` or `wslconfig /u Arch2`

**Comment by ruizlenato** [comment]
![image](https://user-images.githubusercontent.com/49354525/85244586-806d8800-b41b-11ea-943a-596827df7efe.png)
How remove this?

**Comment by yuk7** [comment]
Please move it to the trash bin.

**Comment by ruizlenato** [comment]
Thanks
