### ISSUE TITLE
can't open Arch2

### ISSUE THREAD

**Issue by Sherlock-Holo** [yuk7/ArchWSL2#9]
After install the exe, and set it wsl version to 2, it report

> nsenter: cannot open /proc/12/ns/cgroup: No such file or directory

**Comment by ghost** [comment]
You are not on WSL 2 I think. I had the same issue before, I wasn't in WSL 2 mode when I got that error, fixed with using WSL 2.

**Comment by Sherlock-Holo** [comment]
yes I forget something need to do before using wsl2. Problem is fixed
